# Generated by Django 4.2.7 on 2023-11-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('hindi', models.IntegerField(default=0)),
                ('english', models.IntegerField(default=0)),
                ('maths', models.IntegerField(default=0)),
                ('science', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('perecent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
